Bug/enable com timeseries postprocessing
NREL/buildstockbatch pull request #238
Opened 2021-06-22 03:49 UTC by asparke2

Fixes #237

## Pull Request Description

The default commercial workflow generator was changed to mimic the residential workflow generator, where a new `timeseries_csv_export` key was added to the workflow schema in order to trigger timeseries postprocessing.  The key/value pairs under this key set the arguments to the `TimeseriesCSVExport` measure in the workflow, whereas they were previously hard-coded in the workflow generator.

```
  args:
    reporting_measures:
       - measure_dir_name: qoi_report
    - measure_dir_name: simulation_settings_check
      arguments:
        run_sim_settings_checks: true
    timeseries_csv_export:
      reporting_frequency: Timestep
      inc_output_variables: false
```

## Checklist

Not all may apply

- [x] Code changes (must work)
- [ ] Tests exercising your feature/bug fix (check coverage report on CircleCI build -> Artifacts)
- [ ] All other unit tests passing
- [x] Update validation for project config yaml file changes
- [x] Update existing documentation
- [x] Run a small batch run to make sure it all works (local is fine, unless an Eagle specific feature)
- [x] Add to the changelog_dev.rst file and propose migration text in the pull request

2021-06-22 13:35 UTC, asparke2 commented
@nmerket I can't tell if this is failing because of something in my change or something weird with dockerhub.

2021-06-28 20:00 UTC, asparke2 commented
@nmerket I re-ran the tests and they passed, might have hit the dockerhub limit the other day.

2021-07-07 21:19 UTC, nmerket reviewed
This seems like it should be fine. Sorry it took me so long to see. Is there any way you could write a quick test for this? You'd add it somewhere around [here](https://github.com/NREL/buildstockbatch/blob/bug/enable_com_timeseries_postprocessing/buildstockbatch/workflow_generator/test_workflow_generator.py#L319)

2021-08-13 13:45 UTC, asparke2 commented
@nmerket I don't know how to test this if the CI isn't actually performing runs, any ideas? We've been using this branch for ComStock runs for about a month now, so it's working in practice.

2021-08-13 18:17 UTC, nmerket commented
@asparke2 You can see in some of the other tests there that it's just checking the workflow output to make sure things end up in the right place. It's more lower level testing than you're thinking. I'm not going to force you to add the tests. It's code that only you guys use, so if it breaks, it's your funeral. 

Ultimately we should be doing more full stack integration testing. Maybe once we switch over to github actions so we can use docker from inside the tests properly.

2022-09-16 22:11 UTC, asparke2 commented
@nmerket I've tested this PR on Eagle and on local docker on Windows and Mac. The local docker versions both work, but are ~5-10x slower than Eagle, especially on Windows, presumably because of slow Docker drivers.

2022-10-03 17:13 UTC, nmerket requested changes
See some minor notes below.

You could also improve performance locally by using a [volume mount](https://docker-py.readthedocs.io/en/stable/volumes.html) into the container rather than a bind mount from a folder on the host. That creates a new volume that is only available to the containers but it doesn't have to do all the translation between the host and container, so it's more performant. I know at one point bind mounts were implemented via a network drive, so yeah, no wonder it's slow. Also it would have the benefit of not needing to have a hidden folder to keep the gems on the host, the `.custom_gems` folder. You'd just make the volume, use it, and then delete it when the batch is done.

Finally, could you add something to `changelog_dev.rst` about this? Is there anything else needed in the documentation for people to know how to use it?

2022-10-03 17:13 UTC, nmerket commented on buildstockbatch/localdocker.py
> +        run_cmd = 'openstudio run -w in.osw'
Using a list for the program arguments was an intentional choice. It allows us to more easily manipulate the arguments later without having to deal with whether we got the spaces in there correctly.

2022-10-03 17:13 UTC, nmerket commented on buildstockbatch/localdocker.py
> +            run_cmd += ' --measures_only'
Case in point here. What if that space was missing. Very easy mistake to make.

2022-10-03 17:13 UTC, nmerket commented on buildstockbatch/localdocker.py
> +                       '--bundle_without native_ext run -w in.osw --debug'
You'll need to make other changes to make this work, but yeah.

```suggestion
            run_cmd = [
                'openstudio',
                '--bundle', f'{mnt_custom_gem_dir}/Gemfile',
                '--bundle_path', mnt_custom_gem_dir,
                '--bundle_without native_ext',
                'run', '-w', 'in.osw', '--debug'
            ]
```

2022-10-03 17:18 UTC, nmerket commented
Oh and one more thing. It looks like our already abysmal testing coverage is even lower. I encourage you to write some simple tests to make sure your code is working as you expect. In this case you'd just write something that initializes LocalDockerBatch and make sure it does the things you want. Mocking is very useful there. I can help with that as necessary.

2022-10-14 16:35 UTC, nmerket reviewed
A couple more things and we can merge this

- [ ] I'd like to run a couple small resstock runs on both localdocker and Eagle just to make sure we didn't break anything with this. I don't want everyone coming with their pitchforks.
- [ ] Needs a changelog entry
- [ ] Is there any other documentation that needs to be updated?

2022-10-14 21:59 UTC, nmerket commented
Did a test run on Eagle and Local Docker. Worked Great.

2022-10-17 16:07 UTC, asparke2 commented
No documentation change necessary, already modified the example config in `commercial_default.rst`

2022-10-17 16:11 UTC, asparke2 commented
Did a ComStock local docker test run with custom gems, worked correctly.

2022-10-17 16:23 UTC, nmerket commented
I did some ResStock runs on both Eagle and locally and it worked fine.

2022-10-17 16:26 UTC, nmerket commented
There should definitely be some documentation in project_defn.rst about how to use the custom gems.

2022-10-17 16:28 UTC, nmerket commented
It looks like you do have some documentation [here](https://github.com/NREL/buildstockbatch/blob/bug/enable_com_timeseries_postprocessing/docs/project_defn.rst#baseline-simulations-incl-sampling-algorithm) but it's pretty outdated at this point. Can you update it to reflect the current state of things?

2022-10-18 12:18 UTC, asparke2 commented
@nmerket I added documentation changes for custom gems and did a successful test run on Eagle.

2022-10-19 16:13 UTC, nmerket approved these changes
Thanks for doing all the testing and everything.

2022-10-19 16:13 UTC, nmerket commented on buildstockbatch/test/test_postprocessing.py
> +            patch.object(postprocessing, 'MAX_PARQUET_MEMORY', 1):  # set the max memory to just 1MB
Good catch.

2022-10-19 16:13 UTC, nmerket commented on docs/project_defn.rst
> +  uses the custom gems.
Thanks for updating the docs.

2022-10-19 16:13 UTC, merged