Exclude None from default_na list when reading csv files
NREL/buildstockbatch pull request #374
Opened 2023-05-26 23:30 UTC by rajeee

[Pandas 2.0 introduced](https://pandas.pydata.org/docs/dev/whatsnew/v2.0.0.html#other-api-changes):

> Added "None" to default na_values in read_csv()

This causes issues and breaking change from previous version when reading buildstock.csv or other files that has the string "None". This PR adds a custom read_csv function that restores previous behavior. It should also fix #373.

2023-06-08 21:02 UTC, nmerket requested changes
Looks pretty good. Well done on the testing. Can you add an entry to the changelog?

Also, could you require `pandas>2` in setup.py for this? It probably won't work with pandas 1.x anymore.

2023-06-08 21:02 UTC, nmerket commented on .github/workflows/ci.yml
> +          sudo apt install -y ./OpenStudio-3.6.1+bb9481519e-Ubuntu-20.04-x86_64.deb
Is the new version of OpenStudio required for this? It looks like @joseph-robertson has updated it in #351 as well.

2023-06-08 21:02 UTC, nmerket commented on buildstockbatch/base.py
> +    def validate_buildstock_csv(project_file, buildstock_df):
What's this doing? Tell me in the changelog.

2023-06-08 21:05 UTC, rajeee commented on .github/workflows/ci.yml
> +          sudo apt install -y ./OpenStudio-3.6.1+bb9481519e-Ubuntu-20.04-x86_64.deb
Yeah, the develop was missing this update to CI so I did is as a part of the PR. Whichever PR get's merged last will have to update from develop.

2023-06-08 21:14 UTC, rajeee commented on buildstockbatch/base.py
> +    def validate_buildstock_csv(project_file, buildstock_df):
Done.

2023-06-08 21:15 UTC, rajeee commented
> Looks pretty good. Well done on the testing. Can you add an entry to the changelog?
> 
> Also, could you require `pandas>2` in setup.py for this? It probably won't work with pandas 1.x anymore.

Thanks. It should still work for pandas 1.x.

2023-06-08 22:35 UTC, nmerket reviewed
Should let it be equal to as well.

2023-06-08 22:35 UTC, nmerket commented on setup.py
> +        'pandas>2.0',
```suggestion
        'pandas>=2',
```

2023-06-12 14:22 UTC, nmerket approved these changes

2023-06-12 14:22 UTC, merged

2023-06-12 14:50 UTC, afontani commented
Thanks, @nmerket and @rajeee!